import { z } from "zod";

/**
 * Boundary schema for the certificate code that arrives from a URL segment.
 *
 * The verification route is public and unauthenticated, so this is the only
 * thing standing between a scanned QR (or a hand-typed guess) and a database
 * lookup. Parse, do not cast (rule 4).
 *
 * The character class is deliberately narrow — codes are generated by this
 * system in the shape `HT-CERT-2026-000481`, so anything outside
 * `[A-Za-z0-9-]` is not a truncated code, it is someone probing. Rejecting it
 * before the query keeps malformed input away from the data layer entirely.
 */
export const certificateCodeSchema = z
  .string()
  .trim()
  .min(6)
  .max(64)
  .regex(/^[A-Za-z0-9-]+$/, "Invalid certificate code.");

export type CertificateCode = z.infer<typeof certificateCodeSchema>;
