import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { AuthorRow } from "@/features/forum/author-row";
import {
  CATEGORY_ACCENT_CLASS,
  CATEGORY_BADGE_CLASS,
  CATEGORY_ICONS,
  categoryLabel,
} from "@/features/forum/category-meta";
import { PostEngagementBar } from "@/features/forum/post-engagement-bar";
import { ReplyCard } from "@/features/forum/reply-card";
import { ReplyForm } from "@/features/forum/reply-form";
import { cn } from "@/lib/utils";

// Cannot find module '@/server/services/forum.service' / '@/server/auth/
// session' is expected until DATA-2/AUTH land those — see forum/page.tsx for
// the full contract disclaimer. Expected shape:
//   getPostById(id: string, currentUserId?: string): Promise<ForumPostDetail | null>
import { getSession } from "@/server/auth/session";
import { getPostById } from "@/server/services/forum.service";

// Next 16 requires PageProps<'/forum/[id]'> generated by `npx next typegen`
// (.claude/rules/30-nextjs-16.md #1) and params/searchParams arrive as
// Promises — never destructure them synchronously.
export default async function ForumPostPage(props: PageProps<"/forum/[id]">) {
  const { id } = await props.params;
  const session = await getSession();
  const post = await getPostById(id, session?.userId);

  if (!post) notFound();

  const CategoryIcon = post.category ? CATEGORY_ICONS[post.category] : null;

  return (
    <div className="mx-auto max-w-3xl space-y-6 px-4 pt-24 pb-20 sm:px-6 sm:pt-28">
      {/* Breadcrumb (mobile-01.md #28: "← Forum / Troubleshooting"). */}
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Link href="/forum" className="inline-flex items-center gap-1.5 hover:text-foreground">
          <ArrowLeft className="size-4" aria-hidden /> Forum
        </Link>
        {post.category ? (
          <>
            <span>/</span>
            <span className={CATEGORY_ACCENT_CLASS[post.category]}>{categoryLabel(post.category)}</span>
          </>
        ) : null}
      </div>

      <Card>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-center gap-2">
            {post.category ? (
              <Badge variant="outline" className={cn("gap-1", CATEGORY_BADGE_CLASS[post.category])}>
                {CategoryIcon ? <CategoryIcon className="size-3" aria-hidden /> : null}
                {categoryLabel(post.category)}
              </Badge>
            ) : null}
            {post.hashtags.map((tag) => (
              <span key={tag} className="text-xs text-primary">
                #{tag}
              </span>
            ))}
          </div>

          <h1 className="font-heading text-2xl font-bold text-foreground sm:text-3xl">{post.title}</h1>

          <AuthorRow author={post.author} createdAt={post.createdAt} />

          <Separator />

          <p className="text-sm whitespace-pre-line text-foreground/90">{post.body}</p>

          <PostEngagementBar post={post} />
        </CardContent>
      </Card>

      <div className="flex items-center gap-3 text-sm text-muted-foreground">
        <Separator className="flex-1" />
        <span>
          💬 {post.counts.reply} {post.counts.reply === 1 ? "Reply" : "Replies"}
        </span>
        <Separator className="flex-1" />
      </div>

      {session ? (
        <ReplyForm postId={post.id} />
      ) : (
        <div className="rounded-2xl border border-dashed border-glass-border p-6 text-center text-sm text-muted-foreground">
          💬{" "}
          <Link href="/login" className="font-semibold text-primary hover:underline">
            Sign in
          </Link>{" "}
          to join the conversation
        </div>
      )}

      <div
        className="max-h-[min(62dvh,42rem)] space-y-3 overflow-y-auto overscroll-contain pr-2"
        tabIndex={0}
        data-lenis-prevent
        aria-label="Post replies"
      >
        {post.replies.map((reply) => (
          <ReplyCard key={reply.id} reply={reply} />
        ))}
      </div>

      <div className="flex justify-center pt-4">
        <Link
          href="/forum"
          className="inline-flex items-center gap-1.5 rounded-lg border border-glass-border px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-glass-hover"
        >
          <ArrowLeft className="size-4" aria-hidden /> Back to Forum
        </Link>
      </div>
    </div>
  );
}
